<?php
// filepath: c:\xampp\htdocs\Projet_Vite_Gourmand_Finale\app\Config\pages.php

return [
    'publiques' => [
        'home',
        'login',
        'signin',
        'search',
        'details-menu',
        'filter',
        'contact',
        'contact-success',
        'mention',
        '404',
        'error-ban',
        'forgot-password',
        'reset-password'
    ],

    'existante' => [
        'home',
        'login',
        'signin',
        'logout',
        'search',
        'details-menu',
        'order-menu',
        'order-success',
        'ajax-frais-livraison',
        'filter',
        'contact',
        'contact-success',
        'mention',
        '404',
        'error-ban',
        'ban-user',
        'unban-user',
        'forgot-password',
        'reset-password',
        'update-profil',
        'edit-order',
        'recalculer-prix',
        'recalculer-prix-common',
        'cancel-edit-order',
        'update-order',
        'dashboard-user',
        'review',
        'store-review',

        'dashboard-employee',
       
        'dashboard-admin',
        'stats-admin',
        'rh-admin',
        'rh-admin-create',
        'rh-admin-delete',
        'rh-admin-toggle',
        'ban-user-admin',
        'ban-action-admin',
        'unban-action-admin',
         'ban-user',
        'unban-user',
        
        

        'menu-management',
        'order-management',
        'cancel-order-common',
        'edit-order-common',
        'create-plat-ajax',
        'update-order-common',
        'update-order-status',
        'edit-menu',
        'update-menu-process',
        'add-menu-process',
        'delete-menu',
        'activate-menu',
        'erase-order',
        'review-management',
        'update-review-status',
        'contact-material-client'
    ],

    'admin' => [
        'dashboard-admin',
        'stats-admin',
        'rh-admin',
        'rh-admin-create',
        'rh-admin-delete',
        'rh-admin-toggle',
        'ban-user-admin',
        'ban-action-admin',
        'unban-action-admin',
         'ban-user',
        'unban-user',
       ],

    'employee' => [
        'dashboard-employee',
        
    ],

    'staff' => [
       
        'tickets',
        'delete-tickets',
        'menu-management',
        'order-management',
        'cancel-order-common',
        'edit-order-common',
        'update-order-common',
        'update-order-status',
        'edit-menu',
        'update-menu-process',
        'add-menu-process',
        'create-plat-ajax',
        'delete-menu',
        'activate-menu',
        'review-management',
        'update-review-status',
        'recalculer-prix-common',
        'error-ban',
        'contact-material-client'
    ],

    'user' => [
        'dashboard-user',
        'update-profil',
        'order-menu',
        'order-success',
        'erase-order',
        'ajax-frais-livraison',
        'edit-order',
        'recalculer-prix',
        'cancel-edit-order',
        'update-order',
        'review',
        'store-review',
        'recalculer-prix'
    ],
];
